[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pnutux"
version = "0.2.0"
description = "the ultimate penguin simulator with zero features and 100% gambling addiction"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
pnutux = "tux.main:run_game"

[tool.hatch.build.targets.wheel]
packages = ["src/tux"]
